---

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"

- name: Check kitchen user exists
  user: name={{ kitchen_user }}
  when: >
    ansible_distribution != 'OpenBSD' and
    ansible_os_family != 'Darwin' and
    ansible_os_family != "Alpine" and
    kitchen_user is defined and kitchen_user

- debug: var=kitchen_deps
- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: check if lxd present
  stat: path=/var/lib/lxd
  register: havelxd
## FIXME! not idempotent?
- name: add jenkins to lxd group
  user: name=jenkins groups=lxd append=yes
  when: havelxd.stat.exists

- name: check if docker present
  stat: path=/var/lib/docker
  register: havedocker
- block:
    - name: add jenkins to docker group
      user: name=jenkins groups=docker append=yes
    - name: add jenkins to sudoers for docker
      lineinfile:
        dest: /etc/sudoers.d/99-jenkins-docker
        line: "jenkins   ALL=(root) NOPASSWD{{ ':' }} /usr/bin/docker"
        mode: '0440'
        create: yes
        backup: yes
        validate: 'visudo -cf %s'
  when: havedocker.stat.exists
